name: Dev Release
on: [push, workflow_dispatch]
env:
  BUILD_TYPE: Release
jobs:
  dev-release:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [SF6]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DDEVELOPER_MODE=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}
          path: ${{github.workspace}}/build/bin/${{matrix.target}}/dinput8.dll
          if-no-files-found: error

      - name: Set output
        id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v0.1.13
        with:
          repository: agersant/REFramework
          name: ${{format('v1.{0}-{1}', github.run_number, steps.vars.outputs.SHA_SHORT)}}
          tag_name: latest
          files: ${{github.workspace}}/build/bin/${{matrix.target}}/dinput8.dll
